const ACTIONS = {
  ITEM_SAVE: 'ITEM_SAVE',
  ITEM_EDIT: 'ITEM_EDIT',
  ITEM_REMOVE: 'ITEM_REMOVE',
  ITEM_CHANGE_TITLE: 'ITEM_CHANGE_TITLE',
  ITEM_CHANGE_PRICE: 'ITEM_CHANGE_PRICE',
  ITEM_CLEAR: 'ITEM_CLEAR'
}

export default ACTIONS;